### ISSUE TITLE
Example of access with API tokens

### ISSUE THREAD

**Issue by yildirimatcioglu** [RedMadRobot/fastlane-plugin-jira_release_notes#4]
hello, is there any documentation or example fastfile for accessing with API Tokens

**Comment by Alexander-Ignition** [comment]
Hello, @yildirimatcioglu  

access with an API token works the same way as with a password. 

more example on the [link](https://github.com/RedMadRobot/fastlane-plugin-jira_release_notes/blob/master/fastlane/Fastfile)

```ruby
notes = jira_release_notes(
  username: "me",
  password: "api-token-abc",
  url:      "https://jira.example.com",
  project:  "OX",
  version:  "0.1",
  foramt: "plain"
)
```

**Comment by yildirimatcioglu** [comment]
where to put the access token?

**Comment by yildirimatcioglu** [comment]
please add this to read me or example fast file with a comment.
It works! Thank you have a nice day.

**Comment by Alexander-Ignition** [comment]
access token is passed by the `password ` key

**Comment by Alexander-Ignition** [comment]
Thank you @yildirimatcioglu , I updated the readme
